import type { LucideIcon } from "lucide-react";
import {
  Award,
  BarChart3,
  BookOpen,
  Bot,
  Briefcase,
  Building2,
  CheckCircle2,
  Clapperboard,
  Clock,
  Cpu,
  Flag,
  Globe,
  Heart,
  Layers,
  Lightbulb,
  MapPin,
  Megaphone,
  MessageCircle,
  Palette,
  Radio,
  Rocket,
  Search,
  Shield,
  ShoppingCart,
  Sparkles,
  Target,
  TrendingUp,
  Users,
  Workflow,
  CircleDot,
  PenLine,
  Film,
  Store,
  Wand2,
} from "lucide-react";

/** Lucide icons used by MediaSlot.icon (service page placeholders, etc.). */
export const mediaLucideIcons = {
  Target,
  Palette,
  Sparkles,
  Rocket,
  ChartPie: BarChart3,
  TrendingUp,
  Megaphone,
  Cpu,
  Search,
  Bot,
  Clapperboard,
  ShoppingCart,
  Radio,
  Users,
  Layers,
  Lightbulb,
  Shield,
  Workflow,
  Globe,
  CircleDot,
  Award,
  BookOpen,
  Briefcase,
  Building2,
  CheckCircle2,
  Clock,
  Flag,
  Heart,
  MapPin,
  MessageCircle,
  PenLine,
  Film,
  Store,
  Wand2,
} as const satisfies Record<string, LucideIcon>;

export type MediaLucideName = keyof typeof mediaLucideIcons;

const KEYWORD_ICONS: Array<[RegExp, MediaLucideName]> = [
  [/ai|bot|automat/i, "Bot"],
  [/search|seo|aeo|geo|on-page|technical seo|visibility icon/i, "Search"],
  [/video|film|motion|clapper|play|brand films/i, "Clapperboard"],
  [/market|retail|e-?commerce|listing|catalogue|store|cart|shelf/i, "ShoppingCart"],
  [/social|community|creator|ugc|megaphone|listening|amplif|always-on content/i, "Megaphone"],
  [/chat|message|conversation/i, "MessageCircle"],
  [/tech|platform|integrat|erp|workflow|ops|monitor|cpu|digital platform/i, "Cpu"],
  [/data|analytic|insight|chart|dashboard|report|decision/i, "ChartPie"],
  [/performance|growth|conversion|funnel|billings|scale|optim|retention/i, "TrendingUp"],
  [/strateg|position|target|consult|pilot/i, "Target"],
  [/identity|brand(?! films)|palette|expression|branding/i, "Palette"],
  [/experience|design|spark|innovat|creative craft|wand/i, "Sparkles"],
  [/launch|campaign|rocket|activate|go live/i, "Rocket"],
  [/awareness|consideration|loyalty|engagement|radio/i, "Radio"],
  [/team|people|proven|collaborat|inclusion|great people|networks/i, "Users"],
  [/system|layer|end-to-end|full.?spectrum|full.?funnel|omnichannel/i, "Layers"],
  [/integrity|trust|govern|shield|transpar|honest/i, "Shield"],
  [/local|globe|presence|multi.?platform|markets|nearby/i, "Globe"],
  [/light|idea|content architect|creative solutions/i, "Lightbulb"],
  [/process|workflow/i, "Workflow"],
  [/award|recogni|medal|trophy/i, "Award"],
  [/learn|book|education|train/i, "BookOpen"],
  [/brief|job|department|career|work area/i, "Briefcase"],
  [/agency|enterprise|building|office/i, "Building2"],
  [/check|quality|excellence|ready|proven work/i, "CheckCircle2"],
  [/time|clock|balance|flex|schedule|calendar/i, "Clock"],
  [/owner|accountab|flag|lead/i, "Flag"],
  [/heart|passion|well.?being|meaningful|care/i, "Heart"],
  [/map|pin|location|city/i, "MapPin"],
  [/pen|write|copy|content(?! architect)|story/i, "PenLine"],
  [/film|cinema|production/i, "Film"],
  [/shop|storefront|listing excellence/i, "Store"],
  [/adapt|rapid|format|craft/i, "Wand2"],
];

/** Pick a Lucide icon name from a free-text label (service page placeholders). */
export function lucideNameForLabel(label: string): MediaLucideName {
  for (const [pattern, name] of KEYWORD_ICONS) {
    if (pattern.test(label)) return name;
  }
  return "CircleDot";
}
