import type { CaseStudy } from "@/content/types";

export const ajantaAiCreatives: CaseStudy = {
    slug: "ajanta-ai-creatives",
    client: "Ajanta",
    campaign: "Ajanta Magic Moments",
    industry: "consumer-retail",
    services: ["ai-solutions", "video-production"],
    hero: "A fairy-led magic metaphor, produced end-to-end with AI-assisted craft.",
    challenge: "Produce a premium, Swarovski-inspired creative film on an accelerated timeline.",
    objective: "For Ajanta Magic Moments, our focus wasn't on showcasing a product, but on translating an idea into an experience.",
    mandate: [],
    executionSummary: "",
    execution: [],
    executionPillars: [],
    tags: ["AI", "Video"],
    gallery: [],
    resultHighlights: [
      "AI was integrated across every stage — scripting, storyboarding, visuals, motion, voiceover and music — to deliver Ajanta Magic Moments with a premium aesthetic.",
      "A fairy served as a visual metaphor for magic, while Swarovski-inspired detailing established a premium aesthetic.",
      "The film was completed with custom-composed music and a carefully crafted voiceover.",
    ],
    heroVideo: true,
    video: { title: "Ajanta Magic Moments", description: "AI-assisted film with fairy metaphor, custom music and crafted voiceover.", src: "/videos/work/ajanta-ai-creatives-1.mp4", portrait: true, rotate: "ccw" },
    clientLogo: "/images/partners/clients/ajanta-quartz.png",
    flagship: true,
    featured: true,
    family: "ai",
    accentColor: "#D8CBA9",
  };
