import type { CaseStudy } from "@/content/types";

export const royaleToucheStayCurious: CaseStudy = {
    slug: "royale-touche-stay-curious",
    client: "Royale Touché",
    campaign: "#StayCurious",
    industry: "consumer-retail",
    services: ["seo", "ai-solutions", "influencer-marketing", "social-media"],
    hero: "A Reddit presence of 120K impressions that translated into LLM recognition — 4.9/5.",
    challenge: "Build awareness and communicate the full-size laminate experience across 200+ Experience Centres.",
    objective: "Create awareness and communicate that you can experience the full-size laminate sheet across Royale Touché’s 200+ Experience Centres.",
    mandate: [
      "Drive footfalls at Royale Touché Experience Centres through digital-first campaign adaptations",
      "Build awareness that shoppers can experience the full-size laminate sheet in-store",
      "Amplify the #StayCurious TVC across social, influencer, PR and paid channels",
    ],
    executionSummary: "Multiple digital-first #StayCurious adaptations integrated across platforms — channels, off-beat ads, four influencer phases, earned media, and Reddit → LLM recognition.",
    execution: [
      "Created multiple digital-first adaptations of #StayCurious and integrated them across platforms to drive Experience Centre footfalls",
      "Frequent social posting, large influencer activations, blogs and PR, social ads, contests, programmatic and impact video ads",
      "Channels created: PR articles for healthy backlinks, AI-enabled chatbot for engagement, dedicated store-locator page for each Experience Centre",
      "Off-the-beat ad types and local store visit promotion ads",
      "Phase 1 — Brand Film Buzz: 50 top interior designers and architects (pan-India) resharing the brand film as reposts and stories",
      "Phase 2 — Marketing communities (Mad Over Marketing, Social Samosa, Marketing Maverick, Marketing Mind) campaign breakdowns of the TVC",
      "Phase 3 — Unique influencer content around the TVC with store visits showcasing USPs",
      "Phase 4 — Content seeding with interior designers creating trend-led content monthly for recall and credibility",
      "Earned media: Prince of Udaipur Experience Centre visit, Google review testimonials, contest engagements",
      "Reddit: 8 handles, 9 subreddits, 120K impressions, 150+ engagements → LLM rating 4.9/5 and ChatGPT citations",
    ],
    executionPillars: [
      { title: "Digital System", description: "Social, ads, contests, programmatic and impact video across platforms." },
      { title: "Channels Created", description: "PR backlinks, AI chatbot and store-locator pages for each Experience Centre." },
      { title: "Influencer Phases", description: "Brand film buzz → marketing communities → unique creator content → monthly seeding." },
      { title: "Reddit → LLM", description: "8 handles, 9 subreddits, 120K+ impressions — 4.9/5 LLM rating and ChatGPT source citations." },
    ],
    results: [
      { label: "Experience Centres", value: "200+" },
      { label: "Reddit impressions", value: "120K+" },
      { label: "Reddit engagements", value: "150+" },
      { label: "Reddit handles / subreddits", value: "8 / 9" },
      { label: "LLM rating", value: "4.9/5" },
      { label: "LLM impact", value: "Cited in ChatGPT & LLMs" },
    ],
    tags: ["Integrated", "Influencer", "SEO", "Reddit", "AI"],
    hashtag: "#StayCurious",
    linkGroups: [
      {
        title: "Phase 1 — Brand Film Buzz (Reposts & Stories)",
        description:
          "50 top interior designers and architects pan-India reshared the #StayCurious brand film as reposts and stories.",
        links: [
          { label: "Pragya", description: "Live reel", href: "https://www.instagram.com/reel/C0g0DcKPYCv/" },
          { label: "StudioAdmix", description: "Live reel", href: "https://www.instagram.com/reel/C0hLCStyO20/" },
          { label: "Cubix Global", description: "Live reel", href: "https://www.instagram.com/reel/C0lygnJooPl/" },
          { label: "Ananya Bhatterjee", description: "@interiormaata", href: "https://www.instagram.com/interiormaata/" },
          { label: "Ashwini Dongare", description: "@interiorsbyashwiiniidongare", href: "https://www.instagram.com/interiorsbyashwiiniidongare/" },
          { label: "Sonika Khurrana", description: "@coloraza_interiordesign", href: "https://www.instagram.com/coloraza_interiordesign/" },
          { label: "Nihara", description: "@nihara_iosis", href: "https://www.instagram.com/nihara_iosis/" },
        ],
      },
      {
        title: "Phase 2 — Marketing Communities",
        description:
          "Premium A&M pages broke down the Royale Touché TVC and the core idea behind #StayCurious.",
        links: [
          { label: "Mad Over Marketing", description: "Campaign breakdown", href: "https://www.instagram.com/madovermarketing_mom/p/C1EV5TDy5oh/" },
          { label: "Social Samosa", description: "Campaign breakdown", href: "https://www.instagram.com/p/C0_t5VHoJHG/" },
          { label: "Marketing Maverick", description: "Campaign breakdown", href: "https://www.instagram.com/p/C0_t5VHoJHG/" },
          { label: "Marketing Mind", description: "Campaign breakdown", href: "https://www.instagram.com/madovermarketing_mom/p/C1EV5TDy5oh/" },
        ],
      },
    ],
    galleryGroups: [
      {
        title: "Campaign Cover",
        images: [
          "/images/work/gallery/royale-touche-stay-curious/01.png",
        ],
      },
      {
        title: "Objective & Digital Adaptations",
        images: [
          "/images/work/gallery/royale-touche-stay-curious/02.png",
          "/images/work/gallery/royale-touche-stay-curious/03.jpg",
        ],
      },
      {
        title: "Digital Platforms Used",
        images: [
          "/images/work/gallery/royale-touche-stay-curious/04.png",
        ],
      },
      {
        title: "Channels Created",
        images: [
          "/images/work/gallery/royale-touche-stay-curious/05.jpg",
          "/images/work/gallery/royale-touche-stay-curious/06.jpg",
          "/images/work/gallery/royale-touche-stay-curious/07.jpg",
        ],
      },
      {
        title: "Off-the-Beat Ad Types",
        images: [
          "/images/work/gallery/royale-touche-stay-curious/08.png",
          "/images/work/gallery/royale-touche-stay-curious/09.png",
          "/images/work/gallery/royale-touche-stay-curious/10.png",
          "/images/work/gallery/royale-touche-stay-curious/11.png",
        ],
      },
      {
        title: "Influencer Reposts & Stories",
        images: [
          "/images/work/gallery/royale-touche-stay-curious/12.png",
          "/images/work/gallery/royale-touche-stay-curious/13.png",
          "/images/work/gallery/royale-touche-stay-curious/14.png",
          "/images/work/gallery/royale-touche-stay-curious/15.png",
          "/images/work/gallery/royale-touche-stay-curious/16.png",
          "/images/work/gallery/royale-touche-stay-curious/17.png",
          "/images/work/gallery/royale-touche-stay-curious/18.png",
        ],
      },
      {
        title: "Marketing Communities",
        images: [
          "/images/work/gallery/royale-touche-stay-curious/19.png",
          "/images/work/gallery/royale-touche-stay-curious/20.png",
          "/images/work/gallery/royale-touche-stay-curious/21.png",
          "/images/work/gallery/royale-touche-stay-curious/22.png",
        ],
      },
      {
        title: "Unique Influencer Content",
        images: [
          "/images/work/gallery/royale-touche-stay-curious/23.png",
          "/images/work/gallery/royale-touche-stay-curious/24.png",
          "/images/work/gallery/royale-touche-stay-curious/25.png",
          "/images/work/gallery/royale-touche-stay-curious/26.png",
        ],
      },
      {
        title: "Earned Media",
        images: [
          "/images/work/gallery/royale-touche-stay-curious/27.png",
          "/images/work/gallery/royale-touche-stay-curious/28.png",
          "/images/work/gallery/royale-touche-stay-curious/29.jpg",
          "/images/work/gallery/royale-touche-stay-curious/30.jpg",
          "/images/work/gallery/royale-touche-stay-curious/31.jpg",
        ],
      },
      {
        title: "Reddit Presence",
        images: [
          "/images/work/gallery/royale-touche-stay-curious/32.png",
          "/images/work/gallery/royale-touche-stay-curious/33.png",
        ],
      },
      {
        title: "LLM Recognition",
        images: [
          "/images/work/gallery/royale-touche-stay-curious/34.png",
          "/images/work/gallery/royale-touche-stay-curious/35.png",
        ],
      },
    ],
    gallery: [
      "/images/work/cases/royale-touche.png",
      "/images/work/gallery/royale-touche-stay-curious/01.png",
      "/images/work/gallery/royale-touche-stay-curious/02.png",
      "/images/work/gallery/royale-touche-stay-curious/03.jpg",
      "/images/work/gallery/royale-touche-stay-curious/04.png",
      "/images/work/gallery/royale-touche-stay-curious/05.jpg",
      "/images/work/gallery/royale-touche-stay-curious/06.jpg",
      "/images/work/gallery/royale-touche-stay-curious/07.jpg",
      "/images/work/gallery/royale-touche-stay-curious/08.png",
      "/images/work/gallery/royale-touche-stay-curious/09.png",
      "/images/work/gallery/royale-touche-stay-curious/10.png",
      "/images/work/gallery/royale-touche-stay-curious/11.png",
      "/images/work/gallery/royale-touche-stay-curious/12.png",
      "/images/work/gallery/royale-touche-stay-curious/13.png",
      "/images/work/gallery/royale-touche-stay-curious/14.png",
      "/images/work/gallery/royale-touche-stay-curious/15.png",
      "/images/work/gallery/royale-touche-stay-curious/16.png",
      "/images/work/gallery/royale-touche-stay-curious/17.png",
      "/images/work/gallery/royale-touche-stay-curious/18.png",
      "/images/work/gallery/royale-touche-stay-curious/19.png",
      "/images/work/gallery/royale-touche-stay-curious/20.png",
      "/images/work/gallery/royale-touche-stay-curious/21.png",
      "/images/work/gallery/royale-touche-stay-curious/22.png",
      "/images/work/gallery/royale-touche-stay-curious/23.png",
      "/images/work/gallery/royale-touche-stay-curious/24.png",
      "/images/work/gallery/royale-touche-stay-curious/25.png",
      "/images/work/gallery/royale-touche-stay-curious/26.png",
      "/images/work/gallery/royale-touche-stay-curious/27.png",
      "/images/work/gallery/royale-touche-stay-curious/28.png",
      "/images/work/gallery/royale-touche-stay-curious/29.jpg",
      "/images/work/gallery/royale-touche-stay-curious/30.jpg",
      "/images/work/gallery/royale-touche-stay-curious/31.jpg",
      "/images/work/gallery/royale-touche-stay-curious/32.png",
      "/images/work/gallery/royale-touche-stay-curious/33.png",
      "/images/work/gallery/royale-touche-stay-curious/34.png",
      "/images/work/gallery/royale-touche-stay-curious/35.png",
    ],
    resultHighlights: [
      "Reddit presence successfully translated into LLM recognition",
      "Reddit discussions now cited as source material in ChatGPT and other LLM platforms",
      "Durability insights sourced from Reddit discussions",
      "Customer sentiment aggregated across platforms",
    ],
    video: { title: "#StayCurious Film", description: "Impact video and campaign film for the #StayCurious Experience Centre push.", src: "/videos/work/royale-touche-stay-curious-1.mp4", poster: "/images/work/gallery/royale-touche-stay-curious/01.png" },
    clientLogo: "/images/partners/clients/royale-touche.png",
    flagship: true,
    featured: true,
    family: "integrated",
  };
