import type { CaseStudy } from "@/content/types";

export const royaleToucheStayCurious: CaseStudy = {
    slug: "royale-touche-stay-curious",
    client: "Royale Touché",
    campaign: "#StayCurious",
    industry: "consumer-retail",
    services: ["seo", "ai-solutions", "influencer-marketing", "social-media"],
    hero: "A Reddit presence of 120K impressions that translated into LLM recognition — 4.9/5.",
    challenge: "Build awareness and communicate the full-size laminate experience across 200+ Experience Centres.",
    objective: "Create awareness and communicate that you can experience the full-size laminate sheet across Royale Touché’s 200+ Experience Centres.",
    mandate: [
      "Drive footfalls at Royale Touché Experience Centres through digital-first campaign adaptations",
      "Build awareness that shoppers can experience the full-size laminate sheet in-store",
      "Amplify the #StayCurious TVC across social, influencer, PR and paid channels",
    ],
    executionSummary:
      "Created multiple digital-first adaptations of the #StayCurious campaign and integrated them across platforms to drive footfalls at Experience Centres — frequent social posting, large influencer activations, blogs and PR, social ads, contests, programmatic and impact video ads.",
    execution: [
      "Created multiple digital-first adaptations of #StayCurious and integrated them across platforms to drive Experience Centre footfalls",
      "Frequent social posting, large influencer activations, blogs and PR, social ads, contests, programmatic and impact video ads",
      "Channels created: PR articles for healthy backlinks, AI-enabled chatbot for engagement, dedicated store-locator page for each Experience Centre",
      "Off-the-beat ad types and local store visit promotion ads",
      "Phase 1 — Brand Film Buzz: 50 top interior designers and architects (pan-India) resharing the brand film as reposts and stories",
      "Phase 2 — Marketing communities (Mad Over Marketing, Social Samosa, Marketing Maverick, Marketing Mind) campaign breakdowns of the TVC",
      "Phase 3 — Unique influencer content around the TVC with store visits showcasing USPs",
      "Phase 4 — Content seeding with interior designers creating trend-led content monthly for recall and credibility",
      "Earned media: Prince of Udaipur Experience Centre visit, Google review testimonials, contest engagements",
      "Reddit: 8 handles, 9 subreddits, 120K impressions, 150+ engagements → LLM rating 4.9/5 and ChatGPT citations",
    ],
    executionPillars: [],
    results: [
      { label: "Experience Centres", value: "200+" },
      { label: "Reddit impressions", value: "120K+" },
      { label: "Reddit engagements", value: "150+" },
      { label: "Reddit handles / subreddits", value: "8 / 9" },
      { label: "LLM rating", value: "4.9/5" },
      { label: "LLM impact", value: "Cited in ChatGPT & LLMs" },
    ],
    tags: ["Integrated", "Influencer", "SEO", "Reddit", "AI"],
    linkGroups: [],
    galleryGroups: [
      {
        title: "Digital Platforms Used",
        density: "compact",
        description:
          "Platforms activated across the #StayCurious campaign — search, social, publishers, OTT, commerce and mobile branding.",
        images: [
          "/images/work/gallery/royale-touche-stay-curious/platforms-01.png",
          "/images/work/gallery/royale-touche-stay-curious/platforms-02.png",
          "/images/work/gallery/royale-touche-stay-curious/platforms-03.png",
          "/images/work/gallery/royale-touche-stay-curious/platforms-04.png",
          "/images/work/gallery/royale-touche-stay-curious/platforms-05.png",
          "/images/work/gallery/royale-touche-stay-curious/platforms-06.png",
          "/images/work/gallery/royale-touche-stay-curious/platforms-07.png",
          "/images/work/gallery/royale-touche-stay-curious/platforms-08.png",
          "/images/work/gallery/royale-touche-stay-curious/platforms-09.png",
          "/images/work/gallery/royale-touche-stay-curious/platforms-10.png",
          "/images/work/gallery/royale-touche-stay-curious/platforms-11.png",
          "/images/work/gallery/royale-touche-stay-curious/platforms-12.png",
          "/images/work/gallery/royale-touche-stay-curious/platforms-13.png",
        ],
      },
      {
        title: "Channels Created",
        density: "solo",
        pairRow: "channels-ads",
        description:
          "PR articles to drive healthy backlinks. AI-enabled chatbot for user engagement. Dedicated store-locator page for each Experience Centre.",
        images: [
          {
            src: "/images/work/gallery/royale-touche-stay-curious/06.jpg",
            href: "https://economictimes.indiatimes.com/industry/services/retail/royale-touche-plans-to-expand-its-retail-footprint/articleshow/79428945.cms",
          },
          "/images/work/gallery/royale-touche-stay-curious/05.jpg",
          "/images/work/gallery/royale-touche-stay-curious/07.jpg",
        ],
      },
      {
        title: "Off-the-Beat Ad Types",
        density: "solo",
        pairRow: "channels-ads",
        description:
          "Interactive digital-first adaptations — room revamp experiences and off-the-beat formats built for the #StayCurious push.",
        images: [
          "/images/work/gallery/royale-touche-stay-curious/08-01.png",
          "/images/work/gallery/royale-touche-stay-curious/08-02.png",
          "/images/work/gallery/royale-touche-stay-curious/08-03.png",
          "/images/work/gallery/royale-touche-stay-curious/08-04.png",
        ],
      },
      {
        title: "Local Store Visit Promotion Ads",
        density: "solo",
        pairRow: "channels-ads",
        description:
          "Local store visit promotion ads — map pins, directions CTAs and store cards to drive Experience Centre footfalls.",
        images: [
          "/images/work/gallery/royale-touche-stay-curious/36.png",
          "/images/work/gallery/royale-touche-stay-curious/09.png",
          "/images/work/gallery/royale-touche-stay-curious/10.png",
        ],
      },
      {
        title: "Phase 1 — Brand Film Buzz",
        density: "solo",
        pairRow: "influencer-phases",
        pairRowHeading: "Influencer Activity",
        description:
          "To amplify and create buzz about the launch of the Royale Touché TVC with interior designers across social media for awareness and brand recall. Activated 50 top interior designers and architects (pan-India) to reshare the brand film as reposts and stories.",
        images: [
          {
            src: "/images/work/gallery/royale-touche-stay-curious/12.png",
            href: "https://www.instagram.com/interiormaata/",
          },
          {
            src: "/images/work/gallery/royale-touche-stay-curious/13.png",
            href: "https://www.instagram.com/interiorsbyashwiiniidongare/",
          },
          {
            src: "/images/work/gallery/royale-touche-stay-curious/14.png",
            href: "https://www.instagram.com/coloraza_interiordesign/",
          },
          {
            src: "/images/work/gallery/royale-touche-stay-curious/15.png",
            href: "https://www.instagram.com/nihara_iosis/",
          },
          {
            src: "/images/work/gallery/royale-touche-stay-curious/16.png",
            href: "https://www.instagram.com/reel/C0g0DcKPYCv/",
          },
          {
            src: "/images/work/gallery/royale-touche-stay-curious/17.png",
            href: "https://www.instagram.com/reel/C0hLCStyO20/",
          },
          {
            src: "/images/work/gallery/royale-touche-stay-curious/18.png",
            href: "https://www.instagram.com/reel/C0lygnJooPl/",
          },
        ],
      },
      {
        title: "Phase 2 — Marketing Communities",
        density: "solo",
        pairRow: "influencer-phases",
        description:
          "Premium A&M pages like Mad Over Marketing and Social Samosa delivered a complete campaign breakdown of the Royale Touché TVC — highlighting the core idea behind #StayCurious and driving significant reach and engagement.",
        images: [
          {
            src: "/images/work/gallery/royale-touche-stay-curious/19.png",
            href: "https://www.instagram.com/p/C1eI8c3S06I/",
          },
          {
            src: "/images/work/gallery/royale-touche-stay-curious/20.png",
            href: "https://www.instagram.com/madovermarketing_mom/p/C1EV5TDy5oh/",
          },
          {
            src: "/images/work/gallery/royale-touche-stay-curious/21.png",
            href: "https://www.instagram.com/p/C0_t5VHoJHG/",
          },
          {
            src: "/images/work/gallery/royale-touche-stay-curious/22.png",
            href: "https://www.instagram.com/p/C1CbWmPyG0O/",
          },
        ],
      },
      {
        title: "Phase 3 — Unique Influencer Content",
        density: "solo",
        pairRow: "influencer-phases",
        description:
          "Collaborated with influencers who created captivating videos around the Royale Touché TVC. They visited Royale Touché stores, maintaining excitement and showcasing unique selling points — significantly boosting awareness and interest. Featuring Technocrat Anshul and Oak Kitchen.",
        images: [
          "/images/work/gallery/royale-touche-stay-curious/23.png",
          "/images/work/gallery/royale-touche-stay-curious/24.png",
        ],
      },
      {
        title: "Phase 4 — Content Seeding",
        density: "solo",
        pairRow: "influencer-phases",
        description:
          "To keep the virality of the campaign, content seeding was done with interior designers who created trend-led content that helped brand recall and built credibility on a monthly basis. Featuring Luxury Property Vlogs and Salman Surf.",
        images: [
          "/images/work/gallery/royale-touche-stay-curious/25.png",
          "/images/work/gallery/royale-touche-stay-curious/26.png",
        ],
      },
      {
        title: "Earned Media",
        density: "solo",
        pairRow: "earned-llm",
        description:
          "Prince of Udaipur visiting the Royale Touché Experience Centre. Followers gained. Testimonials via Google Reviews. Drove engagements via contests.",
        images: [
          "/images/work/gallery/royale-touche-stay-curious/27.png",
          "/images/work/gallery/royale-touche-stay-curious/28.png",
          {
            src: "/images/work/gallery/royale-touche-stay-curious/29.jpg",
            href: "https://www.instagram.com/p/CV0lv3nj3M5/",
          },
          "/images/work/gallery/royale-touche-stay-curious/30.jpg",
          "/images/work/gallery/royale-touche-stay-curious/31.jpg",
        ],
      },
      {
        title: "LLM Impact",
        density: "solo",
        pairRow: "earned-llm",
        description:
          "Reddit presence successfully translated into LLM recognition — 4.9/5 LLM rating. Discussions now cited as source material in ChatGPT and other LLM platforms. Durability insights sourced from Reddit discussions. Customer sentiment aggregated across platforms.",
        images: [
          "/images/work/gallery/royale-touche-stay-curious/34.png",
          "/images/work/gallery/royale-touche-stay-curious/35.png",
        ],
      },
    ],
    gallery: [
      "/images/work/gallery/royale-touche-stay-curious/03.jpg",
      "/images/work/gallery/royale-touche-stay-curious/platforms-01.png",
      "/images/work/gallery/royale-touche-stay-curious/platforms-02.png",
      "/images/work/gallery/royale-touche-stay-curious/platforms-03.png",
      "/images/work/gallery/royale-touche-stay-curious/platforms-04.png",
      "/images/work/gallery/royale-touche-stay-curious/platforms-05.png",
      "/images/work/gallery/royale-touche-stay-curious/platforms-06.png",
      "/images/work/gallery/royale-touche-stay-curious/platforms-07.png",
      "/images/work/gallery/royale-touche-stay-curious/platforms-08.png",
      "/images/work/gallery/royale-touche-stay-curious/platforms-09.png",
      "/images/work/gallery/royale-touche-stay-curious/platforms-10.png",
      "/images/work/gallery/royale-touche-stay-curious/platforms-11.png",
      "/images/work/gallery/royale-touche-stay-curious/platforms-12.png",
      "/images/work/gallery/royale-touche-stay-curious/platforms-13.png",
      "/images/work/gallery/royale-touche-stay-curious/06.jpg",
      "/images/work/gallery/royale-touche-stay-curious/05.jpg",
      "/images/work/gallery/royale-touche-stay-curious/07.jpg",
      "/images/work/gallery/royale-touche-stay-curious/08-01.png",
      "/images/work/gallery/royale-touche-stay-curious/08-02.png",
      "/images/work/gallery/royale-touche-stay-curious/08-03.png",
      "/images/work/gallery/royale-touche-stay-curious/08-04.png",
      "/images/work/gallery/royale-touche-stay-curious/36.png",
      "/images/work/gallery/royale-touche-stay-curious/09.png",
      "/images/work/gallery/royale-touche-stay-curious/10.png",
      "/images/work/gallery/royale-touche-stay-curious/12.png",
      "/images/work/gallery/royale-touche-stay-curious/13.png",
      "/images/work/gallery/royale-touche-stay-curious/14.png",
      "/images/work/gallery/royale-touche-stay-curious/15.png",
      "/images/work/gallery/royale-touche-stay-curious/16.png",
      "/images/work/gallery/royale-touche-stay-curious/17.png",
      "/images/work/gallery/royale-touche-stay-curious/18.png",
      "/images/work/gallery/royale-touche-stay-curious/19.png",
      "/images/work/gallery/royale-touche-stay-curious/20.png",
      "/images/work/gallery/royale-touche-stay-curious/21.png",
      "/images/work/gallery/royale-touche-stay-curious/22.png",
      "/images/work/gallery/royale-touche-stay-curious/23.png",
      "/images/work/gallery/royale-touche-stay-curious/24.png",
      "/images/work/gallery/royale-touche-stay-curious/25.png",
      "/images/work/gallery/royale-touche-stay-curious/26.png",
      "/images/work/gallery/royale-touche-stay-curious/27.png",
      "/images/work/gallery/royale-touche-stay-curious/28.png",
      "/images/work/gallery/royale-touche-stay-curious/29.jpg",
      "/images/work/gallery/royale-touche-stay-curious/30.jpg",
      "/images/work/gallery/royale-touche-stay-curious/31.jpg",
      "/images/work/gallery/royale-touche-stay-curious/34.png",
      "/images/work/gallery/royale-touche-stay-curious/35.png",
    ],
    resultHighlights: [
      "Reddit presence successfully translated into LLM recognition",
      "Reddit discussions now cited as source material in ChatGPT and other LLM platforms",
      "Durability insights sourced from Reddit discussions",
      "Customer sentiment aggregated across platforms",
    ],
    video: {
      title: "#StayCurious Film",
      description: "Impact video and campaign film for the #StayCurious Experience Centre push.",
      src: "/videos/work/royale-touche-stay-curious-1.mp4",
      poster: "/images/work/gallery/royale-touche-stay-curious/03.jpg",
    },
    heroVideo: true,
    clientLogo: "/images/partners/clients/royale-touche.png",
    builtWithServices: [],
    flagship: true,
    featured: true,
    family: "integrated",
  };
