import type { CaseStudy } from "@/content/types";

export const caseStudies: CaseStudy[] = [
  {
    slug: "fedex-csk",
    client: "FedEx",
    campaign: "FedEx × Chennai Super Kings",
    industry: "consumer-retail",
    services: ["media-buying"],
    hero: "1.2B+ impressions from an IPL association built for more than logo placement.",
    challenge:
      "Go beyond logo placement to drive real brand visibility and recall — reaching mass consumers and core SME/business audiences through IPL scale.",
    execution: [
      "JioHotstar CTV-only mid-rolls with mobile + TV squeeze-ups",
      "Programmatic live-sync formats, in-banner video, match-event triggered messaging",
      "Hyperlocal OOH strategy tied to CSK player relevance",
      "Core digital across YouTube, Meta, LinkedIn and X, including fraud-awareness KOL content",
    ],
    results: [
      { label: "Impressions", value: "1,204M" },
      { label: "Reach", value: "175M" },
      { label: "Frequency", value: "6.9x" },
      { label: "Video views", value: "85M" },
      { label: "Engagements", value: "54M" },
      { label: "YouTube VTR", value: "61.10%" },
      { label: "Meta VTR", value: "47.80%" },
      { label: "Brand search growth", value: "42%" },
      { label: "Absolute brand lift", value: "3.6%" },
    ],
    flagship: true,
    featured: true,
    family: "media-performance",
    accentColor: "#FFC20E",
  },
  {
    slug: "vip-industries",
    client: "VIP Industries",
    campaign: "Turning Visibility Into Visits",
    industry: "consumer-retail",
    services: ["media-buying"],
    hero: "64M+ impressions converted into measured footfall across 180+ stores.",
    challenge:
      "Accelerate D2C growth by converting awareness into measurable website traffic and store visits.",
    execution: [
      "Audience intelligence and distinct audience cohorts",
      "Full-funnel strategy from video to offer-led performance",
      "Influencer-led creative and hyperlocal CTA campaigns",
      "Footfall measurement across 180+ stores via InMobi",
    ],
    results: [
      { label: "Impressions", value: "64M+" },
      { label: "Reach", value: "13M+" },
      { label: "Clicks", value: "72K+" },
      { label: "Video views", value: "4M+" },
      { label: "Engagements", value: "3M+" },
      { label: "VTR", value: "8.23%" },
      { label: "CTR", value: "0.13%" },
      { label: "Page views", value: "912K" },
      { label: "Measured footfalls", value: "2K" },
    ],
    flagship: true,
    featured: true,
    family: "media-performance",
  },
  {
    slug: "godrej-blue",
    client: "Godrej Properties",
    campaign: "Godrej Blue",
    industry: "real-estate",
    services: ["branding", "influencer-marketing"],
    hero: "A citywide Kolkata takeover — from Howrah Bridge to a Guinness World Record.",
    challenge:
      "Make the launch synonymous with Godrej Properties' entry into Kolkata and create citywide top-of-mind recall.",
    execution: [
      "75+ prime hoardings and 25 LED outdoor billboards",
      "Howrah Bridge illumination and landmark takeovers — South City Mall, Big Ben Clock Tower, Acropolis Mall, Kolkata Airport",
      "Celebrity collaborations, print, and an Amazon packaging partnership",
      "1,000+ influencers activated live within one hour, setting a Guinness World Record",
    ],
    results: [
      { label: "Prime hoardings", value: "75+" },
      { label: "LED billboards", value: "25" },
      { label: "Influencers live in 1 hour", value: "1,000+" },
      { label: "Recognition", value: "Guinness World Record" },
    ],
    flagship: true,
    featured: true,
    family: "integrated",
    accentColor: "#1E4FA3",
  },
  {
    slug: "mahindra-manulife",
    client: "Mahindra Manulife",
    campaign: "Ground-up Digital Reinvention",
    industry: "bfsi",
    services: ["technology"],
    hero: "A ground-up rebuild of web and mobile platforms for a regulated financial business.",
    challenge:
      "Legacy transaction flows, fragmented integrations and no unified architecture — against strict compliance and audit requirements.",
    execution: [
      "Rebuilt purchase journeys across web and mobile",
      "Payment gateway and registrar integrations",
      "Compliance infrastructure and full audit trail",
      "Unified transaction architecture across five-plus critical integrations",
    ],
    results: [
      { label: "Platforms rebuilt", value: "2" },
      { label: "Critical integrations", value: "5+" },
      { label: "Transaction re-engineering", value: "End-to-end" },
      { label: "Outcome", value: "Faster time-to-market for new fund offerings" },
    ],
    flagship: true,
    featured: true,
    family: "technology",
  },
  {
    slug: "orpat-erp",
    client: "Orpat",
    campaign: "Manufacturing ERP Transformation",
    industry: "technology-manufacturing-energy",
    services: ["technology"],
    hero: "A purpose-built ERP that unified raw material to dispatch across a manufacturing operation.",
    challenge:
      "Streamline complex cross-functional manufacturing workflows spanning raw material, SKU-level production, BOM, quality control, finished goods, dispatch, sales, accounts and HR.",
    execution: [
      "Purpose-built ERP aligned to actual operating workflows",
      "Cross-functional visibility from shop floor to accounts",
    ],
    results: [
      { label: "Adoption", value: "Strong" },
      { label: "Visibility", value: "Improved cross-functional" },
      { label: "Planning", value: "More accurate material planning" },
      { label: "Coordination", value: "Better control across teams" },
    ],
    family: "technology",
  },
  {
    slug: "akbar-travels-seo",
    client: "Akbar Travels",
    campaign: "SEO Growth",
    industry: "travel-hospitality",
    services: ["seo"],
    hero: "Visa leads grew from 1,000+ to 20,000+ a month through SEO alone.",
    challenge: "Compete against major OTAs and government visa-search properties.",
    execution: [
      "Keyword mapping and primary/secondary page architecture",
      "Internal linking and CTA improvement",
      "WhatsApp lead capture",
      "Trend-based blogs, PR and guest blogging",
    ],
    results: [
      { label: "Traffic growth", value: "130%+" },
      { label: "Visa leads (monthly)", value: "1,000+ → 20,000+" },
      { label: "Top 3 non-brand keywords", value: "165% improvement" },
      { label: "AI Overview visibility", value: "Significant" },
    ],
    flagship: true,
    featured: true,
    family: "media-performance",
  },
  {
    slug: "shoppers-stop-local-seo",
    client: "Shoppers Stop",
    campaign: "Local SEO",
    industry: "consumer-retail",
    services: ["seo"],
    hero: "Turning weak local visibility into stronger store-level discovery.",
    challenge: "Low local visibility, limited reviews and weak Google Business Profile optimisation.",
    execution: [
      "Corrected NAP, images, business hours and service information",
      "Review generation and review response management",
      "Local keyword targeting and GMB content",
    ],
    results: [
      { label: "Local visibility", value: "Improved" },
      { label: "Store footfall", value: "Increased" },
      { label: "Profile interaction", value: "Higher" },
      { label: "Reviews & credibility", value: "Improved" },
    ],
    family: "media-performance",
  },
  {
    slug: "cello-kidzbee",
    client: "Cello Kidzbee",
    campaign: "Back to School",
    industry: "consumer-retail",
    services: ["video-production"],
    hero: "A visually rich campaign film turned around in under a week.",
    challenge: "Position Kidzbee products as vibrant and essential school companions.",
    execution: ["First cut delivered in 3–4 days", "Full production completed in 6–7 days"],
    results: [
      { label: "Turnaround", value: "6–7 days" },
      { label: "First cut", value: "3–4 days" },
      { label: "Revisions", value: "Minimal" },
    ],
    family: "content-social",
  },
  {
    slug: "young-bags",
    client: "Young Bags",
    campaign: "Brand Repositioning",
    industry: "consumer-retail",
    services: ["video-production"],
    hero: "Repositioning a functional bags brand as contemporary and youthful.",
    challenge: "Reposition Young Bags as contemporary, dynamic, youthful, stylish and functional.",
    execution: ["High-quality visual content production", "Style and functionality balanced in a single narrative"],
    results: [
      { label: "Turnaround", value: "6–7 days" },
      { label: "Positioning", value: "Youthful repositioning" },
    ],
    family: "content-social",
    accentColor: "#A9906B",
  },
  {
    slug: "ambassador-hotel",
    client: "The Ambassador Hotel",
    campaign: "Brand Experience",
    industry: "travel-hospitality",
    services: ["branding"],
    hero: "Brand identity translated into signage manufactured in Mumbai and installed in Scotland.",
    challenge: "Translate brand identity into a cohesive physical brand experience.",
    execution: [
      "3D metal logo and room signage",
      "Directional signage and menu recreation",
      "Exterior menu boards",
      "Cross-geography manufacturing and installation",
    ],
    results: [
      { label: "Identity", value: "Cohesive on-ground identity" },
      { label: "Production", value: "Mumbai to Scotland" },
      { label: "Craftsmanship", value: "High-precision" },
    ],
    family: "integrated",
    accentColor: "#7A1F2B",
  },
  {
    slug: "godrej-greenfront",
    client: "Godrej Properties",
    campaign: "The Greenfront",
    industry: "real-estate",
    services: ["branding"],
    hero: "Infinite Shades of Green — a campaign built around the site's natural abundance.",
    challenge: "Build a campaign rooted in the site's natural abundance and distinct shades of green.",
    execution: [
      "Green gradient visual system mapped to amenities",
      "Modular visual language across brochure, newspaper, standee and hoarding",
      "Zepto activation with QR-led landing page",
    ],
    results: [
      { label: "Concept", value: "Infinite Shades of Green" },
      { label: "Activation", value: "Offline + digital + Zepto" },
    ],
    flagship: true,
    featured: true,
    family: "integrated",
    accentColor: "#2F7D4F",
  },
  {
    slug: "amazon-samsung-great-indian-festival",
    client: "Amazon × Samsung",
    campaign: "Great Indian Festival 2025",
    industry: "consumer-retail",
    services: ["influencer-marketing"],
    hero: "Positioning the Galaxy M36 5G as the value pick under ₹15K.",
    challenge:
      "Maximise Samsung Galaxy M36 5G visibility, position it as strong value under ₹15K, and build pre-buzz ahead of sale.",
    execution: [
      "Tech reviewers and Hindi creators",
      "Demo-led, hook-led short and long-form storytelling",
      "Flagship comparisons timed to sale rollout",
    ],
    results: [{ label: "Format mix", value: "Short-form + long-form" }],
    family: "content-social",
    accentColor: "#1428A0",
  },
  {
    slug: "adani-airports-safar-ke-humsafar",
    client: "Adani Airports",
    campaign: "Safar Ke Humsafar",
    industry: "travel-hospitality",
    services: ["influencer-marketing"],
    hero: "Real traveller stories built into a UGC-driven campaign of human moments.",
    challenge: "Build mass awareness and emotional engagement around the airport experience.",
    execution: [
      "UGC-driven influencer campaign with real traveller stories",
      "Airport staff moments shot naturally",
      "Social-first Reels with audience story CTA",
    ],
    results: [
      { label: "Engagement", value: "High" },
      { label: "Perception", value: "Stronger people-first perception" },
      { label: "Participation", value: "Organic audience participation" },
    ],
    family: "content-social",
  },
  {
    slug: "poonawalla-fraud-awareness",
    client: "Poonawalla Fincorp",
    campaign: "Fraud Awareness",
    industry: "bfsi",
    services: ["social-media"],
    hero: "Cinema-style storytelling that made fraud awareness resonate.",
    challenge: "Build awareness around everyday financial scams — identity, impersonation, urgency and phishing.",
    execution: [
      "Strong visual hooks and crisp copy",
      "Relatable, dialogue-led educational characters",
      "Cinema-style storytelling",
    ],
    results: [
      { label: "Engagement rate", value: "5.7%" },
      { label: "Resonance", value: "Strong audience resonance" },
    ],
    flagship: true,
    featured: true,
    family: "content-social",
    accentColor: "#1B2A4A",
  },
  {
    slug: "waaree",
    client: "Waaree",
    campaign: "Integrated B2B/B2C Social",
    industry: "technology-manufacturing-energy",
    services: ["social-media"],
    hero: "One unified narrative across B2B and B2C audiences for a solar manufacturing leader.",
    challenge: "Strengthen integrated brand presence across B2B and B2C audiences.",
    execution: [
      "Retainer creative and campaign posts",
      "Short-form video and event-led storytelling",
      "Narrative spanning solar savings, manufacturing scale and market leadership",
    ],
    results: [
      { label: "Visibility", value: "Stronger" },
      { label: "Narrative", value: "Unified across B2B/B2C" },
    ],
    family: "content-social",
    accentColor: "#1F7A4C",
  },
  {
    slug: "ajanta-ai-creatives",
    client: "Ajanta",
    campaign: "Magic Moments — AI for Creatives",
    industry: "consumer-retail",
    services: ["ai-solutions", "video-production"],
    hero: "A fairy-led magic metaphor, produced end-to-end with AI-assisted craft.",
    challenge: "Produce a premium, Swarovski-inspired creative film on an accelerated timeline.",
    execution: [
      "AI applied to scripting, storyboarding, visuals, motion, voiceover and music",
      "Custom music and crafted voiceover layered onto AI-assisted visuals",
    ],
    results: [{ label: "AI role", value: "Creative production accelerator" }],
    flagship: true,
    featured: true,
    family: "ai",
    accentColor: "#D8CBA9",
  },
  {
    slug: "poonawalla-ai-creatives",
    client: "Poonawalla Fincorp",
    campaign: "AI Creative Production",
    industry: "bfsi",
    services: ["ai-solutions", "video-production"],
    hero: "30-second festive story reels, produced with AI across script, visuals and sound.",
    challenge: "Produce story-led festive content at speed without losing craft quality.",
    execution: ["AI applied to script, visuals, voiceover and music for 30-second story-led festive reels"],
    results: [{ label: "AI role", value: "Creative production accelerator" }],
    family: "ai",
  },
  {
    slug: "royale-touche-stay-curious",
    client: "Royale Touché",
    campaign: "#StayCurious",
    industry: "consumer-retail",
    services: ["seo", "ai-solutions", "influencer-marketing", "social-media"],
    hero: "A Reddit presence of 120K impressions that translated into LLM recognition.",
    challenge:
      "Build awareness and communicate the full-size laminate experience across 200+ Experience Centres.",
    execution: [
      "Social posting, influencer activation, blogs, PR and social ads",
      "Contests, programmatic and an impact video",
      "Store locator and an AI chatbot for on-site discovery",
      "Local store ads and content seeding across 8 Reddit handles and 9 subreddits",
    ],
    results: [
      { label: "Experience Centres reached", value: "200+" },
      { label: "Reddit impressions", value: "120K" },
      { label: "Reddit engagements", value: "150+" },
      { label: "Reddit handles / subreddits", value: "8 / 9" },
      { label: "Outcome", value: "LLM recognition" },
    ],
    flagship: true,
    featured: true,
    family: "integrated",
  },
];

export const flagshipCaseStudySlugs = caseStudies.filter((c) => c.flagship).map((c) => c.slug);
export const featuredCaseStudySlugs = caseStudies.filter((c) => c.featured).map((c) => c.slug);
