// GENERATED by scripts/update-content-dates.mjs — do not edit by hand. Regenerate before each release.
// Dates come from git history (last commit touching a page's source files). They feed the sitemap
// <lastmod>, Article dateModified and VideoObject uploadDate.

export const contentDatesGeneratedOn = "2026-10-07";

/** Public path -> date (YYYY-MM-DD) the page's source content last changed. */
export const pageLastModified: Record<string, string> = {
  "/": "2026-10-07",
  "/about": "2026-10-06",
  "/services": "2026-10-06",
  "/work": "2026-10-06",
  "/careers": "2026-10-06",
  "/awards": "2026-10-06",
  "/contact": "2026-10-06",
  "/privacy-policy": "2026-10-06",
  "/services/ai-solutions": "2026-10-06",
  "/services/branding": "2026-10-06",
  "/services/creative": "2026-10-06",
  "/services/guides": "2026-10-06",
  "/services/influencer-marketing": "2026-10-06",
  "/services/marketplace-management": "2026-10-06",
  "/services/media-buying": "2026-10-06",
  "/services/seo": "2026-10-06",
  "/services/social-media": "2026-10-06",
  "/services/technology": "2026-10-06",
  "/services/video-production": "2026-10-06",
  "/work/adani-airports-safar-ke-humsafar": "2026-09-10",
  "/work/ajanta-ai-creatives": "2026-10-06",
  "/work/akbar-travels-seo": "2026-09-10",
  "/work/amazon-samsung-great-indian-festival": "2026-10-06",
  "/work/ambassador-hotel": "2026-10-06",
  "/work/cello-kidzbee": "2026-09-10",
  "/work/fedex-csk": "2026-09-25",
  "/work/godrej-blue": "2026-09-25",
  "/work/godrej-greenfront": "2026-10-06",
  "/work/jockey-seo": "2026-09-28",
  "/work/mahindra-manulife": "2026-10-06",
  "/work/orpat-erp": "2026-10-06",
  "/work/royale-touche-stay-curious": "2026-10-06",
  "/work/vip-industries": "2026-10-06",
  "/work/waaree": "2026-10-06",
};

/** Video file path under /public -> date (YYYY-MM-DD) the file was first added to the site. */
export const videoUploadDates: Record<string, string> = {
  "/videos/work/ajanta-ai-creatives-1.mp4": "2026-08-29",
  "/videos/work/cello-kidzbee-1.mp4": "2026-08-29",
  "/videos/work/fedex-csk-1.mp4": "2026-08-29",
  "/videos/work/fedex-csk-2.mp4": "2026-08-29",
  "/videos/work/fedex-csk-3.mp4": "2026-08-29",
  "/videos/work/godrej-blue-1.mp4": "2026-08-29",
  "/videos/work/godrej-blue-2.mp4": "2026-08-29",
  "/videos/work/godrej-blue-3.mp4": "2026-08-29",
  "/videos/work/royale-touche-stay-curious-1.mp4": "2026-08-29",
};
