import type { Service } from "@/content/types";

export const services: Service[] = [
  {
    slug: "media-buying",
    name: "360° Media Buying",
    shortName: "Media Buying",
    summary:
      "Integrated media strategy across search, social, programmatic, OTT and hyperlocal OOH — planned as one system, not separate buys.",
    heroStatement:
      "We plan media as one connected system, not a stack of separate buys.",
    capabilities: [
      "Integrated media strategy",
      "Performance marketing",
      "Paid search",
      "Paid social",
      "Programmatic",
      "Display",
      "YouTube",
      "OTT",
      "CTV",
      "Mobile",
      "OOH integration",
      "Retail media",
      "Audience planning",
      "Hyperlocal media",
      "Attribution",
      "Analytics",
      "Brand lift",
      "Conversion optimisation",
    ],
    caseStudySlugs: ["fedex-csk", "vip-industries"],
    family: "performance-data",
  },
  {
    slug: "video-production",
    name: "Video Production",
    shortName: "Video Production",
    summary:
      "Brand films, social video and campaign production — increasingly accelerated by AI-assisted workflows without losing craft.",
    heroStatement: "Stories built for how people actually watch today.",
    capabilities: [
      "Brand films",
      "Product films",
      "Social video",
      "Digital films",
      "Motion graphics",
      "Campaign videos",
      "Reels",
      "Short-form production",
      "Post-production",
      "Editing",
      "Storyboarding",
      "AI-assisted production",
    ],
    caseStudySlugs: ["cello-kidzbee", "young-bags", "ajanta-ai-creatives", "poonawalla-ai-creatives"],
    family: "visual-creative",
  },
  {
    slug: "branding",
    name: "Project Innovation & Branding",
    shortName: "Branding",
    summary:
      "Brand strategy and identity carried all the way through to physical, on-ground experience — not just a logo and a deck.",
    heroStatement: "Identity that holds up on a screen and on a storefront.",
    capabilities: [
      "Brand strategy",
      "Brand identity",
      "Campaign platforms",
      "Brand systems",
      "Visual identity",
      "Launch campaigns",
      "Retail branding",
      "On-ground branding",
      "Packaging",
      "Signage",
      "Print",
      "Integrated innovation",
      "Experience design",
    ],
    caseStudySlugs: ["ambassador-hotel", "godrej-greenfront", "godrej-blue"],
    family: "visual-creative",
  },
  {
    slug: "influencer-marketing",
    name: "Influencer Marketing",
    shortName: "Influencer",
    summary:
      "From celebrity collaborations to micro-creator networks, built for scale, authenticity and measurable amplification.",
    heroStatement: "Creators as a system, not a one-off activation.",
    capabilities: [
      "Influencer strategy",
      "Creator discovery",
      "Creator onboarding",
      "UGC",
      "Celebrity creators",
      "Micro / macro creators",
      "Community amplification",
      "Content seeding",
      "Creator events",
      "Influencer media amplification",
      "Reporting",
    ],
    caseStudySlugs: ["amazon-samsung-great-indian-festival", "adani-airports-safar-ke-humsafar", "royale-touche-stay-curious", "godrej-blue"],
    family: "social-creator",
  },
  {
    slug: "marketplace-management",
    name: "Marketplace Management",
    shortName: "Marketplace",
    summary:
      "End-to-end management of brand presence on e-commerce marketplaces — listings, catalogue, store optimisation and promotion.",
    heroStatement: "Marketplace presence, managed as a growth channel.",
    capabilities: [
      "Marketplace platform management",
      "Listing management",
      "Catalogue management",
      "Store optimisation",
      "Marketplace media",
      "Promotion management",
      "Reporting",
    ],
    caseStudySlugs: [],
    family: "product-tech",
  },
  {
    slug: "technology",
    name: "Tech Solutions",
    shortName: "Technology",
    summary:
      "Ground-up digital platforms, ERP builds and system integrations for businesses that have outgrown off-the-shelf software.",
    heroStatement: "We build the systems growth runs on, not just the campaigns.",
    capabilities: [
      "Web platforms",
      "Mobile platforms",
      "Digital transformation",
      "Custom software",
      "ERP",
      "Payment integrations",
      "KYC integrations",
      "Registrar integrations",
      "Compliance systems",
      "Workflow platforms",
      "APIs",
      "Dashboards",
      "Automation",
      "System integration",
    ],
    caseStudySlugs: ["mahindra-manulife", "orpat-erp"],
    family: "product-tech",
  },
  {
    slug: "creative",
    name: "Creative Solutions",
    shortName: "Creative",
    summary:
      "Campaign and performance creative across formats — from static and motion to retail and social-first storytelling.",
    heroStatement: "Creative built to perform, not just to look good.",
    capabilities: [
      "Campaign creative",
      "Digital creative",
      "Performance creative",
      "Social creative",
      "Static / motion",
      "Creative adaptation",
      "Brand systems",
      "Content design",
      "Retail creative",
    ],
    caseStudySlugs: [],
    family: "visual-creative",
  },
  {
    slug: "social-media",
    name: "Social Media Management",
    shortName: "Social",
    summary:
      "Always-on social strategy, content and community management for both B2B and B2C audiences.",
    heroStatement: "Social that compounds, not campaigns in isolation.",
    capabilities: [
      "Social strategy",
      "Content calendars",
      "Social creative",
      "Community management",
      "Always-on content",
      "Campaign content",
      "Social listening",
      "Reporting",
      "Social-first storytelling",
      "B2B social",
      "B2C social",
    ],
    caseStudySlugs: ["poonawalla-fraud-awareness", "waaree"],
    family: "social-creator",
  },
  {
    slug: "seo",
    name: "SEO Solutions",
    shortName: "SEO",
    summary:
      "Technical, on-page and local SEO built for how search actually works now — including AI Overviews, AEO and GEO.",
    heroStatement: "Built to be found — by search engines and by AI.",
    capabilities: [
      "Technical SEO",
      "On-page SEO",
      "Keyword strategy",
      "Content architecture",
      "Internal linking",
      "Local SEO",
      "Google Business Profile",
      "Off-page SEO",
      "Digital PR",
      "Search content",
      "SEO analytics",
      "AEO",
      "GEO",
      "AI Overview optimisation",
    ],
    caseStudySlugs: ["akbar-travels-seo", "shoppers-stop-local-seo", "royale-touche-stay-curious"],
    family: "performance-data",
  },
  {
    slug: "ai-solutions",
    name: "AI Solutions",
    shortName: "AI",
    summary:
      "AI applied across creative production, analytics and search discoverability — a practical accelerator, not a buzzword.",
    heroStatement: "Intelligence built into the system, not bolted on.",
    capabilities: [
      "AI for creative (scripting, storyboarding, visuals, motion, voiceover, music)",
      "AI for analytics (dashboards, real-time insights, decision support)",
      "AI for search (AEO, GEO, LLM visibility)",
      "AI for operations",
    ],
    caseStudySlugs: ["ajanta-ai-creatives", "poonawalla-ai-creatives", "royale-touche-stay-curious"],
    family: "ai",
  },
];
