export const workPhotos: Record<string, string> = {
  "godrej-blue": "/images/work/cases/godrej-blue.png",
  "fedex-csk": "/images/work/cases/fedex-csk.png",
  "royale-touche-stay-curious": "/images/work/cases/royale-touche.png",
  "poonawalla-fraud-awareness": "/images/work/cases/poonawalla-fraud-awareness.png",
  "mahindra-manulife": "/images/work/cases/mahindra-manulife.png",
  "orpat-erp": "/images/work/cases/orpat-erp.png",
  "ajanta-ai-creatives": "/images/work/cases/ajanta-ai-creatives.png",
  waaree: "/images/work/cases/waaree.png",
  "vip-industries": "/images/work/vip-industries.png",
  "akbar-travels-seo": "/images/work/akbar-travels-seo.png",
  "poonawalla-ai-creatives": "/images/work/poonawalla-ai-creatives.png",
  "shoppers-stop-local-seo": "/images/work/cases/shoppers-stop-local-seo.png",
  "cello-kidzbee": "/images/work/cases/cello-kidzbee.png",
  "young-bags": "/images/work/cases/young-bags.png",
  "ambassador-hotel": "/images/work/cases/ambassador-hotel.png",
  "godrej-greenfront": "/images/work/cases/godrej-greenfront.png",
  "amazon-samsung-great-indian-festival":
    "/images/work/cases/amazon-samsung-great-indian-festival.png",
  "adani-airports-safar-ke-humsafar": "/images/work/cases/adani-airports-safar-ke-humsafar.png",
};
