import {
  TrendingUp,
  ChartBar,
  Search,
  Globe,
  ChartColumn,
  Radar,
  Clock,
  Layers,
  MessagesSquare,
  ChartPie,
  Network,
  Share2,
  Users,
  Film,
  Music,
  Image,
  Newspaper,
  Truck,
  CreditCard,
  Camera,
  Megaphone,
  type LucideIcon,
} from "lucide-react";

export const dataToolIcons: Record<string, LucideIcon> = {
  "Google Trends": TrendingUp,
  Comscore: ChartBar,
  SEMrush: Search,
  GWI: Globe,
  "Power BI": ChartColumn,
  Brandwatch: Radar,
  Brand24: Clock,
  Supermetrics: Layers,
  "Konnect Insights": MessagesSquare,
  "Looker Studio": ChartPie,
  Similarweb: Network,
};

export const platformIcons: Record<string, LucideIcon> = {
  Google: Search,
  Meta: Share2,
  LinkedIn: Users,
  Reddit: MessagesSquare,
  JioHotstar: Film,
  Spotify: Music,
  Pinterest: Image,
  "Prime Video": Film,
  Quora: MessagesSquare,
  Inshorts: Newspaper,
  Zepto: Truck,
  Paytm: CreditCard,
  Snapchat: Camera,
  Moneycontrol: TrendingUp,
  "X Ads": Megaphone,
};
